### ISSUE TITLE
UI / Logic: Quiz 

### ISSUE THREAD

**Issue by mwatidy** [mylife-plus/SFW-Microorganism-App#22]
[Wireframe](https://www.figma.com/file/QMm6yXvIhIDIcTLM4nfMEY/SFW-Microorganisms-App?node-id=4%3A0) 

Quiz Screen:  
- Answer selected
- Info
- Canvas with zoom, measurement, and expand 
- Vew Information
- Comments

**Comment by mike-gallego** [comment]
Requesting this issue

**Comment by MouyouMoos** [comment]
paid 100$ to mike-gallego for this issue and @mwatidy checked it but it turned out that the work was not good so we have to do the issue again :( 

https://stellar.expert/explorer/public/tx/03313cd92412e2b3894e54caf9a8f81d4928d4999f2a5371e13facc0c5108c3a

**Work Missing: **

- Changing Answer Categories
- 1 Hour: Refactoring Previous Filter Code from Gallery view.
- 1.5 Hour: Implementing the Filter Function in the Quiz view to provide a Working Selection Menu
- 1 Hour:  Dynamic info Pop-Up and Ruler Functionalities
- 4,5 Hours : Ruler implementation.( Showing Organism Measurements).

**Comment by haythemd** [comment]
---20-10-2021--- PAID
Total: 6.5 Hours * 15$ = 97,5$ 
- 3.5 Hours Finished Implementing the Info Pop-Up the Confirm Pop-Up the Selection Menu 
- 3 Hours Querying the Quiz and Implementing an Infinite Page View :
